package com.fghilmany.nufitai.domain.onboarding.entity

enum class ParQQuestionId {
    Q1_HEART_DIAGNOSIS,
    Q2_CHEST_PAIN_ACTIVITY,
    Q3_CHEST_PAIN_REST,
    Q4_DIZZINESS_FAINTING,
    Q5_BLOOD_PRESSURE,
    Q6_JOINT_PROBLEM,
    Q7_RECENT_SURGERY,
    Q8_ROUTINE_MEDICATION,
    Q9_DIABETES,
    Q10_ACTIVE_CANCER,
    Q11_PREGNANCY,
    Q12_OTHER_CONDITION,
}
